### PR TITLE
Add setting to enable Nvidia dedicated graphics.

### PR DESCRIPTION
**Pull request by reitzig**
Adds a configuration setting to set up the environment for dedicated Nvidia graphics.

cf. https://forum.snapcraft.io/t/im-building-a-mtg-arena-snap-and-have-some-issues/15826

### CODE REVIEW

**Comment by reitzig** [comment]
Currently, with or without the new setting enabled, I'm getting:

```
$ mtg-arena.super-snap                                                                                              
Using Nvidia graphics
Mono path[0] = 'C:/Program Files (x86)/Wizards of the Coast/MTGA/MTGA_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Wizards of the Coast/MTGA/MonoBleedingEdge/etc'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 154 (GLX)
  Request Minor code 6 ()
  Error Serial #197
  Current Serial #196
```

**Comment by the-mentor** [comment]
Hi @reitzig the Nvidia issue you are mentioning is an issue with the snapd from my understanding 
Here is a link to the issue [https://forum.snapcraft.io/t/nvidia-beta-drivers-completely-break-snaps/12392/15](https://forum.snapcraft.io/t/nvidia-beta-drivers-completely-break-snaps/12392/15)

At the moment I'm not sure how to fix it since i think its a problem in the snap piping not this specific snap.

> Currently, with or without the new setting enabled, I'm getting:
> 
> ```
> $ mtg-arena.super-snap                                                                                              
> Using Nvidia graphics
> Mono path[0] = 'C:/Program Files (x86)/Wizards of the Coast/MTGA/MTGA_Data/Managed'
> Mono config path = 'C:/Program Files (x86)/Wizards of the Coast/MTGA/MonoBleedingEdge/etc'
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> X Error:  GLXBadContext
>   Request Major code 154 (GLX)
>   Request Minor code 6 ()
>   Error Serial #197
>   Current Serial #196
> ```

**Comment by reitzig** [comment]
I don't think I have beta drivers installed on my machine; they are the official nvidia drivers, far as I can tell.

I'm absolutely not sure whether one has to install drivers _in_ the snap, or link the host drivers correctly. Maybe someone on the snapcraft forums can help.

**Comment by the-mentor** [comment]
@reitzig I opened a bug for this issue in snapd let's see what they say.
From my understanding you shouldn't need to install these drivers inside the snap.

**Pull request closed without merging**
